### ISSUE TITLE
No start

### ISSUE THREAD

**Issue by kxknet** [TanVD/ClickhouseCluster_DockerCompose#1]
clickhouse-client --port=9001
ClickHouse client version 19.4.3.11.
Connecting to localhost:9001 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9001, 127.0.0.1)

**Comment by TanVD** [comment]
It would be nice to have some more info. 
It works correctly on my instance. 
Will close ticket for now, and will reopen if new details will be provided.
